#!/bin/sh

set -e

die() {
    echo >&2 "$@"
    exit 1
}

# shellcheck disable=SC1007
TEST_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

# XXX TODO freebsd has "daemon"
if ! command -v daemonize >/dev/null; then
    die "missing required program 'daemonize'"
fi

# XXX TODO lookup package names (debian/ubuntu: netcat-openbsd)
if ! command -v nc >/dev/null; then
    die "missing required program 'nc'"
fi

if ! command -v yq >/dev/null; then
    die "missing required program 'yq'. You can install it with 'GO111MODULE=on go get github.com/mikefarah/yq/v4'"
fi

# shellcheck source=./.environment.sh
. "${TEST_DIR}/.environment.sh"

totest="${TEST_DIR}/bats"
if [ -n "$1" ]; then
    totest=$*
fi

"${TEST_DIR}/bats/lib/bats-core/bin/bats" \
    --jobs 1 \
    --print-output-on-failure \
    -T "$totest"

